# Generated by Django 3.2.13 on 2023-04-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0111_alter_airtableimportjob_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('source_language', models.CharField(blank=True, default='', help_text='Target Language', max_length=255)),
                ('target_language', models.CharField(blank=True, default='', help_text='Target Language', max_length=255)),
                ('source_field', models.ForeignKey(blank=True, help_text='The field to translate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.field')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
    ]
