# Generated by Django 3.2.13 on 2023-08-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0119_field_tsvector_column_created'),
        ('baserow_translate_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('prompt', models.CharField(blank=True, default='', help_text='Prompt for chatgpt', max_length=4096)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
    ]
